name: reviewdog

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: |
          yarn install
      - uses: reviewdog/action-setup@v1
      - name: Run eslint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          yarn run lint:eslint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true

  stylelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: |
          yarn install
      - uses: reviewdog/action-setup@v1
      - name: Run stylelint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          yarn run lint:stylelint --no-color | reviewdog -f=stylelint -reporter=github-pr-review -level=error -filter-mode=nofilter -fail-on-error=false
